// Proxy container recives the event bubble
export const PROPAGATION_OUTERMOST = "PROPAGATION_OUTERMOST"

// Two languages exchanged
export const SWAP_LANGUAGE_COMPLETED = "SWAP_LANGUAGE_COMPLETED"
export const SET_LANGUAGES_FROM_TO = "SET_LANGUAGES_FROM_TO"

// Mask layout is hidden manually by clicking
export const MASK_MANUAL_HIDDEN = "MASK_MANUAL_HIDDEN"

// Some action make page to switch, e.g. drawer"s nav-links were clicked
export const PAGE_IS_SWITCHING = "PAGE_IS_SWITCHING"

// Query text"s length is zero, nothing to translate
export const TRANSLATE_QUERY_NONE = "TRANSLATE_QUERY_NONE"

export const REQUEST_TRANSLATING = "REQUEST_TRANSLATING"
export const RESPOND_TRANSLATING = "RESPOND_TRANSLATING"

// Translation result appears in popup panel
export const TRANSLATE_IN_POPUP = "TRANSLATE_IN_POPUP"

// Translation result appears in float panel of content
export const TRANSLATE_IN_FLOAT = "TRANSLATE_IN_FLOAT"

export const CONNECT_WITH_TRANSLATING = "CONNECT_WITH_TRANSLATING"
export const CONNECT_FROM_BACKGROUND = "CONNECT_FROM_BACKGROUND"
export const CONNECT_FROM_CONTENT = "CONNECT_FROM_CONTENT"

export const RESPONSE_FROM_BACKGROUND = "RESPONSE_FROM_BACKGROUND"

export const MESSAGE_IN_POPUP = "MESSAGE_IN_POPUP"
export const MESSAGE_IN_BACKGROUND = "MESSAGE_IN_BACKGROUND"
export const NO_CONNECT_NAME = "NO_CONNECT_NAME"

export const TRANSLATE_QUERY_DONE = "TRANSLATE_QUERY_DONE"
export const TRANSLATE_WITH_SELECTING = "TRANSLATE_WITH_SELECTING"

export const UPDATE_SETTINGS = "UPDATE_SETTINGS"
export const RESET_SETTINGS = "RESET_SETTINGS"

export const NO_CORRESPONDING_ACTION = "NO_CORRESPONDING_ACTION"

export const UNINSTALL_EXTENSION = "UNINSTALL_EXTENSION"

// Select UI has < 2 options
export const SELECT_LACK_OPTIONS = "SELECT_LACK_OPTIONS"
export const SELECT_OPTION_CHANGED = "SELECT_OPTION_CHANGED"

export const SETTINGS_SET_SUCCESS = "SETTINGS_SET_SUCCESS"
export const SETTINGS_SET_ERROR = "SETTINGS_SET_ERROR"

export const TABS_UPDATE_CONNECT = "TABS_UPDATE_CONNECT"
export const TABS_UPDATE_LOADING = "TABS_UPDATE_LOADING"
export const TABS_UPDATE_COMPLETE = "TABS_UPDATE_COMPLETE"

export const SELECTED_TEXT_IN_CONTENT = "SELECTED_TEXT_IN_CONTENT"
export const REMOVED_SELECTION_IN_CONTENT = "REMOVED_SELECTION_IN_CONTENT"

export const FAB_TRIGGERED = "FAB_TRIGGERED"
export const RENDER_FLOAT_ACTION_PANEL = "RENDER_FLOAT_ACTION_PANEL"
