export const container = document.querySelector('.container')
export const content = container.querySelector('main.content')
export const istream = content.querySelector('section.input-stream')
export const ostream = content.querySelector('section.output-stream')
export const mask = container.querySelector('.mask.-js')
