export const STORAGE_CHANGE = 'STORAGE_CHANGE'

export const STORAGE_LOCAL = 'STORAGE_LOCAL'

export const STORAGE_SYNC = 'STORAGE_SYNC'

export const GET_LANGUAGE_LIST = 'GET_LANGUAGE_LIST'

export const CURRENT_LANGUAGES = 'CURRENT_LANGUAGES'

export const BACKGROUND_INITIALIZE = 'BACKGROUND_INITIALIZE'

export const MERGE_STORAGE_STATE = 'MERGE_STORAGE_STATE'

export const DRAWER_NAGIVATION_TOGGLE = 'DRAWER_NAGIVATION_TOGGLE'

export const COMPILE_SERVICE_SOURCES = 'COMPILE_SERVICE_SOURCES'

export const STORAGE_TYPE_SET = 'STORAGE_TYPE_SET'

export const POPUP_PAGE_INITIAL = 'POPUP_PAGE_INITIAL'

export const CURRENT_SERVICE_SOURCE = 'CURRENT_SERVICE_SOURCE'

export const NEXT_SERVICE_SOURCE = 'NEXT_SERVICE_SOURCE'
