export const INITIAL_BACKGROUND_SCRIPT = 'INITIAL_BACKGROUND_SCRIPT'

export const INITIAL_FROM_BACKGROUND = 'INITIAL_FROM_BACKGROUND'

export const STORAGE_TYPE_SET = 'STORAGE_TYPE_SET'

export const UPDATE_STORAGE_STATE = 'UPDATE_STORAGE_STATE'

export const REQUEST_TRANSLATION = 'REQUEST_TRANSLATION'
