export const INITIAL_STORAGE_FROM_DEFAULT = 'INITIAL_STORAGE_FROM_DEFAULT'

export const INITIAL_BACKGROUND_SCRIPT = 'INITIAL_BACKGROUND_SCRIPT'

export const INITIAL_FROM_BACKGROUND = 'INITIAL_FROM_BACKGROUND'

export const SIMULATE_SEND_MESSAGE = 'SIMULATE_SEND_MESSAGE'

export const STORAGE_TYPE_SET = 'STORAGE_TYPE_SET'

export const UPDATE_STORAGE_STATE = 'UPDATE_STORAGE_STATE'

export const REQUEST_TRANSLATION = 'REQUEST_TRANSLATION'

export const REQUEST_VOICE = 'REQUEST_VOICE'

export const RESET_LOCAL_STORAGE = 'RESET_LOCAL_STORAGE'

export const UNINSTALL_EXTENSION = 'UNINSTALL_EXTENSION'

export const TAB_LOADED_COMPLETE = 'TAB_LOADED_COMPLETE'

export const CREATE_CONTEXT_MENU = 'CREATE_CONTEXT_MENU'

export const REMOVE_CONTEXT_MENU = 'REMOVE_CONTEXT_MENU'

export const CONTEXT_MENU_ACTION_TRANSLATE = 'CONTEXT_MENU_ACTION_TRANSLATE'

export const GET_PAGE_SELECTED_TEXT = 'GET_PAGE_SELECTED_TEXT'

export const SAVE_CUSTOM_SOURCES_PRESET = 'SAVE_CUSTOM_SOURCES_PRESET'

export const FETCH_REQUEST = 'FETCH_REQUEST'
